{% set version = "5.32.1" %}
{% set major_minor_version = version.split(".")[:2] | join(".") %}

package:
  name: perl
  version: {{ version }}

source:
  - url: http://www.cpan.org/src/5.0/perl-{{ version }}.tar.xz
    sha256: 57cc47c735c8300a8ce2fa0643507b44c4ae59012bfdad0121313db639e02309
    patches:
      - 0001-Use-userelocatableinc-together-with-useshrplib.patch  # [unix]
      - 0002-Disable-direct-invocation-of-linker-if-LD-is-set.patch
      - 0003-update-setting-for-conda-directory-structure.patch  # [win]
      - 0004-skip-failing-Net-Ping-test-on-win.patch  # [win]
      - 0005-skip-perlbug-test-that-fails-on-multiple-platforms.patch
      - 0006-allow-t-TTY-to-fail-on-Windows.patch  # [win]
      - 0007-skip-several-tests-on-non-AMD64-unix.patch  # [unix]
      - 0008-skip-newly-failing-Win32-tests.patch  # [win]

build:
  skip: True  # [osx]
  number: 8
  run_exports:
    weak:
      - {{ pin_subpackage("perl", max_pin="x.x") }}
    noarch:
      - {{ pin_subpackage("perl", max_pin="x") }}

requirements:
  build:
    - {{ compiler('c') }}  # [unix]
    - {{ stdlib("c") }}  # [unix]
    - {{ compiler("m2w64_c") }}  # [win]
    - {{ stdlib("m2w64_c") }}  # [win]
    - m2w64-gcc  # [win]
    - m2-patch  # [win] 
    - m2-sed  # [win]
    - make
  host:
    - libxcrypt  # [linux]

test:
  # downstreams:
  #   - git
  #   - automake
  commands:
    - perl --version
    - |  # [unix]
      perl -V:cf_by | grep -qF "'conda'"  # [unix]
      perl -V:cf_email | grep -qF "'conda'"  # [unix]
      perl -V:perladmin | grep -qF "'conda'"  # [unix]
      perl -e 'print "$_\n" for @INC' | grep -qxF "${PREFIX}/lib/perl5/site_perl"  # [unix]
      perl -e 'print "$_\n" for @INC' | grep -qxF "${PREFIX}/lib/perl5/vendor_perl"  # [unix]
      perl -e 'print "$_\n" for @INC' | grep -qxF "${PREFIX}/lib/perl5/core_perl"  # [unix]
      perl -e 'print "$_\n" for @INC' | grep -qxF "${PREFIX}/lib/perl5/{{ major_minor_version }}/site_perl"  # [unix]
      perl -e 'print "$_\n" for @INC' | grep -qxF "${PREFIX}/lib/perl5/{{ major_minor_version }}/vendor_perl"  # [unix]
      perl -e 'print "$_\n" for @INC' | grep -qxF "${PREFIX}/lib/perl5/{{ major_minor_version }}/core_perl"  # [unix]
    # conda replaces back- by forward slashes during prefix placeholder replacement on installs:
    #   This means our Config.pm and Config_heavy.pl etc. carry mixed back-/forward slashes
    #   which Perl seems to handle well, though.
    #   refs:
    #     - https://github.com/conda/conda/blob/4.10.3/conda/core/portability.py#L37-L40
    #     - https://github.com/conda/conda/pull/2630#discussion_r66468372
    - perl -V  # [win]
    - perl -e "print \"$_\n\" for @INC" | findstr /E "lib/perl5/site_perl"  # [win]
    - perl -e "print \"$_\n\" for @INC" | findstr /E "lib/perl5/vendor_perl"  # [win]
    - perl -e "print \"$_\n\" for @INC" | findstr /E "lib/perl5/core_perl"  # [win]
    - perl -e "print \"$_\n\" for @INC" | findstr /E "lib/perl5/{{ major_minor_version }}/site_perl"  # [win]
    - perl -e "print \"$_\n\" for @INC" | findstr /E "lib/perl5/{{ major_minor_version }}/vendor_perl"  # [win]
    - perl -e "print \"$_\n\" for @INC" | findstr /E "lib/perl5/{{ major_minor_version }}/core_perl"  # [win]

about:
  home: http://www.perl.org/
  license: GPL-1.0-or-later OR Artistic-1.0-Perl
  license_file:
    - Artistic
    - Copying
  summary: "The Perl programming language interpreter."
  description: |
    Perl 5 is a highly capable, feature-rich programming language with over 29
    years of development. Perl 5 runs on over 100 platforms from portables to
    mainframes and is suitable for both rapid prototyping and large scale
    development projects.
  doc_url: https://www.perl.org/docs.html
  dev_url: https://github.com/perl/perl5

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - mingwandroid
    - isuruf
    - mbargull
